### ISSUE TITLE
使用obs推流时，服务器必须回车一下才开始收流

### ISSUE THREAD

**Issue by liping17** [Monibuca/plugin-rtmp#1]
![image](https://user-images.githubusercontent.com/46994788/87275966-e1b3e300-c511-11ea-8954-10f1fc800057.png)
而且在播放时只有flv.js可以播放，但播一会就会卡死

**Comment by liping17** [comment]
断开重连下倒是正常了。
stream列表里采样率码率都对不上，一直是0

**Comment by liping17** [comment]
rtmp推，rtmp播正常。自带的jessica里几个播放器都不行

**Comment by liping17** [comment]
![image](https://user-images.githubusercontent.com/46994788/87288681-41b88280-c52e-11ea-9dcb-a71610d21607.png)
录制也报错。和winserver系统有关？

**Comment by langhuihui** [comment]
目录是否已创建好了呢



---原始邮件---
发件人: "liping17"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午5:29
收件人: "Monibuca/plugin-rtmp"<plugin-rtmp@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Monibuca/plugin-rtmp] 使用obs推流时，服务器必须回车一下才开始收流 (#1)




 

 录制也报错。和wenserver系统有关？

**Comment by liping17** [comment]
启动的目录下有这个文件夹
![image](https://user-images.githubusercontent.com/46994788/87289503-50536980-c52f-11ea-9322-1d0503dd5913.png)
