### ISSUE TITLE
关于摄像头推流的问题

### ISSUE THREAD

**Issue by liwilljinx** [Monibuca/plugin-rtmp#12]
小白想请教一下，使用网络摄像头，搭建好流媒体服务器之后，要在摄像头的同一个网段配置一台电脑专门去推流吗，如果有多个摄像头的话是不是就需要多台电脑去推流了

**Comment by langhuihui** [comment]
你是说多个网段都有摄像头是吗？

**Comment by liwilljinx** [comment]
就是不同的网段都有摄像头

**Comment by langhuihui** [comment]
你说的是一种方案，如果能直接访问到摄像头的话，也可以不用那么做

**Comment by liwilljinx** [comment]
直接访问到摄像头的话是需要摄像头有公网ip才可以吗

**Comment by langhuihui** [comment]
这个分很多情况，但是这个属于另一个话题了，你可以自行学习一下

**Comment by liwilljinx** [comment]
好的，谢谢大佬
