### ISSUE TITLE
RTMP的RecvMessage()函数会存在崩溃的可能

### ISSUE THREAD

**Issue by daxiong0327** [Monibuca/plugin-rtmp#22]
![image](https://user-images.githubusercontent.com/79887694/233521241-cf9e4617-1f22-47bb-8751-a325bb5aa0f1.png)

readChunk()在MessageTypeID 等于 RTMP_MSG_CHUNK_SIZE 时，存在body.Len()小于4的情况，这时chunk.MsgData将为nil，msg.MsgData 强转 Uint32Message 就会产生崩溃；
![image](https://user-images.githubusercontent.com/79887694/233521682-dd685980-c62c-48c3-a597-1eb253b2c74f.png)

**Comment by langhuihui** [comment]
return了啊，走不到下面

**Comment by daxiong0327** [comment]
是走不到下面，所以崩溃了
<img width="989" alt="image" src="https://user-images.githubusercontent.com/79887694/233523110-e351bf7f-aa8c-4880-863b-e0219ad60487.png">

**Comment by langhuihui** [comment]
哦哦，我加个判断err是否为空

**Comment by daxiong0327** [comment]
👌
