### ISSUE TITLE
推流监权

### ISSUE THREAD

**Issue by soitun** [Monibuca/plugin-rtmp#3]
请问推流时如何实现用户名密码认证

**Comment by langhuihui** [comment]
项目本身并没有提供用户名密码认证，原因是，认证有很多种方式，实际使用的时候必然需要二次开发，所以只提供一个钩子，用于扩展。其原理如下：
在订阅者的插件中提供触发认证的函数调用，参考jessica插件中的subscriber.go中的代码
```
if err := AuthHooks.Trigger(sign); err != nil {
		w.WriteHeader(403)
		return
}
```

然后需要新增一个专门用于应答的插件，通过监听这个钩子的事件来进行验证，并返回true或者false
如何监听？AuthHooks.AddHook即可。如何开发插件？请到官网查看文档，以及参考现有插件代码。
另外本人还可以提供有偿开发服务。

**Comment by soitun** [comment]
明白，谢谢
