### ISSUE TITLE
播放4k视频卡顿

### ISSUE THREAD

**Issue by ChungTak** [Monibuca/plugin-rtmp#9]
### 测试环境
- 系统: ubuntu 20.04 
- 内存:16G
- CPU: 4.01 GHz 四核Intel Core i7
- 网络： 127.0.0.1本地循环网络
- 测试版本： engine/v2 v2.3.0  plugin-rtmp v1.2.5  默认配置  
### 问题描述
推送一路rtmp，然后ffplay 播放rtmp，画面很卡顿。
测试视频HD.Club-4K-Chimei-inn-20mbps.mp4
下载: http://pan.baidu.com/s/1ntG1d0H 密码: r7ag

**Comment by langhuihui** [comment]
这个主要是时间戳问题引起的，engine重新打了时间戳，这个问题在3.0中已解决。当时这么做的原因是发现OBS推流的时间戳不对，严重滞后，不过现在已经查明原因了，rtmp音视频时间戳共用一套相对时间戳。

**Comment by ChungTak** [comment]
现在3.0 能测试吗？有没有文档介绍怎么搭建起来试试？

**Comment by ChungTak** [comment]
现在3.0 能测试吗？有没有文档介绍怎么搭建起来试试？

**Comment by langhuihui** [comment]
```go
package main

import (
	. "github.com/Monibuca/engine/v3"
	_ "github.com/Monibuca/plugin-gateway/v3"
	_ "github.com/Monibuca/plugin-jessica/v3"
	_ "github.com/Monibuca/plugin-rtmp/v3"
	_ "github.com/Monibuca/plugin-webrtc/v3"
	_ "github.com/Monibuca/plugin-rtsp/v3"
	_ "github.com/Monibuca/plugin-hls/v3"
)

func main() {
	Run("./config.toml")
	select {}
}

```
UI还没弄好
